image: hashicorp/terraform:latest

pipelines:
  default:
    - step:
        name: Terraform Init and Plan
        script:
          - terraform init
          - terraform fmt
          - terraform validate
          - terraform plan -var "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" -var "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" -out=tfplan
          - terraform apply -auto-approve
        artifacts:
          - tfplan

    # - step:
    #     name: Terraform Apply
    #     script:
    #       - terraform apply -auto-approve
    #       - terraform output
    #     artifacts:
    #       - tfplan